---
- name: Template with a loop
  hosts: fry
  connection: ssh
  gather_facts: no

  tasks:
    - name: Running a looping jinja template creating mutiple files with task loop
      template:  
        src: templates/mission-orders.txt.j2    # name of the template on ansible controller
        dest: "~/{{item.mission}}-mission-orders.txt" # name of the completed file to be placed on the target system
      loop: 
        - {"mission": "primary", "planet": "luna park"}
        - {"mission": "secondary", "planet": "cineplex 14"}
      vars:
        planet: "{{ item.planet }}"

