---
- name: Disable CBC and force the latest ciphers and algorithms for SSH
  copy:
    src:  ~/mycode/templates/sshd_config
    dest: /etc/ssh/sshd_config
  become: yes  
  notify:
    - ssh-restart
